{{- $csiHostpathProperties := merge .Values $.Values.global}}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-attacher
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
spec:
  serviceName: "csi-hostpath-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostpath-attacher
  template:
    metadata:
      labels:
        app: csi-hostpath-attacher
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-hostpathplugin
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-attacher
      {{- if or (.Values.dockerRegistrySecret) (.Values.global.dockerRegistrySecret) }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecret | default .Values.global.dockerRegistrySecret }}
      {{- end}}
      containers:
        - name: csi-attacher
          {{- with $csiHostpathProperties.sidecars}}
          image: "{{ .baseRepo }}/{{ .images.externalAttacher.image }}:{{ .images.externalAttacher.tag }}"
          {{- end}}
          imagePullPolicy: Always
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir

      volumes:
        - hostPath:
            path:  {{ $csiHostpathProperties.sidecars.kubeletPath }}/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: socket-dir
